import express from "express";
import authRoutes from "./auth.routes.js";
import studentRoutes from "./student.routes.js";
import adminRoutes from "./admin.routes.js";
import courseRoutes from "./course.routes.js";
import categoryRoutes from "./category.routes.js";
import publicRoutes from "./public.routes.js";
import uploadRoutes from "./upload.routes.js";
import ebookRoutes from "./ebook.routes.js";
import learningRoutes from "./learning.routes.js";
import forumRoutes from "./forum.routes.js";
import paymentRoutes from "./payment.routes.js";
import certificateRoutes from "./certificate.routes.js";
import interactionRoutes from "./interaction.routes.js";
import reviewRoutes from "./review.routes.js";
import examRoutes from "./exam.routes.js";
import userRoutes from "./user.routes.js";
const router = express.Router();
router.get("/health", (req, res) => res.json({ success: true, message: "OK" }));

router.use("/auth", authRoutes);
router.use("/student", studentRoutes);
router.use("/admin", adminRoutes);
router.use("/courses", courseRoutes);
router.use("/categories", categoryRoutes);
router.use("/public", publicRoutes);
router.use("/upload", uploadRoutes);
router.use("/ebooks", ebookRoutes);
router.use("/learning", learningRoutes);
router.use("/forum", forumRoutes);
router.use("/payments", paymentRoutes);
router.use("/certificates", certificateRoutes);
router.use("/interactions", interactionRoutes);
router.use("/reviews", reviewRoutes);
router.use("/exams", examRoutes);
router.use("/users", userRoutes);
export default router;
